name: vmdr
favicon: null
layout_spectrum: 0.9825605468358845
typography_spectrum: 0.5544207743369043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.059814615873619914
  lightness: 0.14409791072830558
  saturation: 0.9503242820501328
  rhythmicContrast: 0.18970969272777438
purpose: []
